In [15]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [16]:
x.requires_grad_(True)  # 等价于x=torch.arange(4.0,requires_grad=True)
x.grad  # 默认值是None(没有导数）

In [17]:
y = 2 * torch.dot(x, x)
# y=2*x1*x1 
# y=2*x2*x2 
# y=2*x3*x3 
# y=2*x4*x4
y

tensor(28., grad_fn=<MulBackward0>)

In [18]:
y.backward()# 对x1 x2 x3 x4分别求导
x.grad # 函数y = 2*x*x 的梯度应该是4x

tensor([ 0.,  4.,  8., 12.])

In [19]:
x.grad == 4 * x

tensor([True, True, True, True])

In [20]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad

tensor([ 0.,  4.,  8., 12.])

In [21]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [22]:
y = x.sum()
y# y=x求导

tensor(6., grad_fn=<SumBackward0>)

In [23]:
y.backward()
x.grad#关于x1 x2 x3 x4求导的值

tensor([1., 1., 1., 1.])

In [24]:
# 对非标量调用backward需要传入一个gradient参数，该参数指定微分函数关于self的梯度。
# 本例只想求偏导数的和，所以传递一个1的梯度是合适的
x.grad


tensor([1., 1., 1., 1.])

In [25]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [26]:
y = x * x 
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [27]:
y.sum().backward()# 先变成标量再求导
x.grad

tensor([0., 2., 4., 6.])

In [28]:
x.grad.zero_()
y = x * x
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [29]:
u = y.detach()
u

tensor([0., 1., 4., 9.])

In [30]:
z = u * x
z

tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>)

In [31]:
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [32]:
x.grad

tensor([0., 1., 4., 9.])